"""CSV views of the DB, written atomically into the shared Dropbox.

The scope PC is the single writer; files are fully rewritten to a temp name and
os.replace()d so Dropbox only ever syncs complete files.
"""

from __future__ import annotations

import csv
import logging
import os
import sqlite3
from pathlib import Path

log = logging.getLogger(__name__)

_README = """These CSV files are generated by after_scope — any manual edits will be
overwritten on the next export. Query the nightly .db backup in ../backup with any
SQLite tool for anything the CSVs don't cover.
"""

_VIEWS: dict[str, str] = {
    "sessions.csv": """
        SELECT s.id AS session_id, u.full_name AS user, u.initials,
               s.started_at, s.ended_at, s.ended_reason, s.status, s.incomplete_reason,
               s.identify_method, s.arrival_state_ok, s.zen_exit_code,
               s.checklist_completed_at, s.app_version
        FROM sessions s LEFT JOIN users u ON u.id = s.user_id
        ORDER BY s.id""",
    "files_catalog.csv": """
        SELECT f.id AS file_id, f.session_id, u.initials AS user, e.name AS experiment,
               f.strain, f.condition, f.coverslip, f.sample_prep, f.notes,
               f.acquired_at, f.objective_name, f.magnification, f.na, f.immersion,
               f.pixel_size_um, f.channels_json, f.dims_json,
               f.status, f.origin, f.original_path, f.current_path, f.size_bytes
        FROM files f
        LEFT JOIN users u ON u.id = f.user_id
        LEFT JOIN experiments e ON e.id = f.experiment_id
        WHERE f.status != 'excluded'
        ORDER BY f.id""",
    "cleaning_log.csv": """
        SELECT c.session_id, u.full_name AS user, c.item_key, c.label_snapshot,
               c.response_json, c.flagged, c.answered_at
        FROM checklist_responses c
        LEFT JOIN sessions s ON s.id = c.session_id
        LEFT JOIN users u ON u.id = s.user_id
        ORDER BY c.session_id, c.id""",
    "maintenance.csv": """
        SELECT m.created_at, m.type, m.objective_name, m.solvent,
               u.full_name AS user, m.session_id, m.notes
        FROM maintenance_events m LEFT JOIN users u ON u.id = m.user_id
        ORDER BY m.created_at""",
    "incidents.csv": """
        SELECT i.id AS incident_id, i.created_at, i.category, i.severity, i.status,
               u.full_name AS reported_by, i.description, i.photo_path,
               i.session_id, i.attributed_session_id, i.resolved_at
        FROM incidents i LEFT JOIN users u ON u.id = i.reported_by
        ORDER BY i.id""",
    "dust_refs.csv": """
        SELECT d.created_at, d.objective_name, d.method, d.notes, d.session_id,
               f.current_path AS file_path
        FROM dust_refs d LEFT JOIN files f ON f.id = d.file_id
        ORDER BY d.id""",
}


def _write_atomic(dest: Path, header: list[str], rows: list[sqlite3.Row]) -> None:
    tmp = dest.with_suffix(dest.suffix + ".tmp")
    with open(tmp, "w", newline="", encoding="utf-8-sig") as f:  # BOM: Excel-friendly
        w = csv.writer(f)
        w.writerow(header)
        for row in rows:
            w.writerow([row[k] for k in header])
    os.replace(tmp, dest)


def export_all(conn: sqlite3.Connection, exports_dir: Path) -> list[Path]:
    """Regenerate every CSV view. Best-effort: Dropbox being offline only logs."""
    written: list[Path] = []
    try:
        exports_dir.mkdir(parents=True, exist_ok=True)
        readme = exports_dir / "README.txt"
        if not readme.exists():
            readme.write_text(_README, encoding="utf-8")
    except OSError:
        log.error("Cannot create exports dir %s", exports_dir, exc_info=True)
        return written
    for name, sql in _VIEWS.items():
        try:
            cur = conn.execute(sql)
            header = [d[0] for d in cur.description]
            _write_atomic(exports_dir / name, header, cur.fetchall())
            written.append(exports_dir / name)
        except (sqlite3.Error, OSError):
            log.error("Export failed for %s", name, exc_info=True)
    return written
